version: "3.8"
services:
  app:
    stdin_open: true
    tty: true
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      # - node_modules:/app/node_modules
    command: bash -c "yarn dev"
    ports:
      - "3000:3000"
      - "51204:51204"

# volumes:
#   node_modules:
